export interface Film {
    PK: string;
    SK: string;
    acceleratedTranscoding: string;
    ageRating: string;
    archiveSource: string;
    awards: string[];
    behindTheScenes: string[];
    boxOfficePerformance: number;
    cast: { name: string; role: string }[];
    cinematographer: string;
    cloudFront: string;
    cmafDashPlaylist: string | null;
    cmafDashUrl: string | null;
    cmafHlsPlaylist: string | null;
    cmafHlsUrl: string | null;
    commentaryTracks: string[];
    costumeDesigner: string;
    countryOfOrigin: string;
    criticRatings: {
      IMDb: number;
      Metacritic: number;
      RottenTomatoes: number;
    };
    dashPlaylist: string | null;
    dashUrl: string | null;
    deletedScenes: string[];
    description: string;
    destBucket: string;
    directors: string[];
    editor: string;
    egressEndpoints: Record<string, any>;
    enableMediaPackage: boolean;
    enableSns: boolean;
    enableSqs: boolean;
    encodeJobId: string;
    endTime: string;
    frameCapture: boolean;
    genres: string[];
    hlsPlaylist: string;
    hlsUrl: string;
    inputRotate: string;
    interviews: string[];
    jobTemplate_720p: string;
    jobTemplate_1080p: string;
    jobTemplate_2160p: string;
    languages: string[];
    mediaPackageResourceId: string;
    mp4Outputs: string[] | null;
    mp4Urls: string[] | null;
    mssPlaylist: string | null;
    mssUrl: string | null;
    musicComposer: string;
    originalTitle: string;
    plotSummary: string;
    posterUrls: string[] | null;
    producers: string[];
    productionDesigner: string;
    productionYear: number;
    releaseDate: string;
    sequelPrequel: {
      prequels: string[];
      sequels: string[];
    };
    seriesInformation: {
      franchise: string;
      chronologicalOrder: number;
      releaseOrder: number;
    };
    similarMovies: string[];
    srcBucket: string;
    srcMediainfo: string;
    srcVideo: string;
    startTime: string;
    subtitleLanguages: string[];
    tags: string[];
    themes: string[];
    thumbNails: string[];
    thumbNailsUrls: string[];
    title: string;
    trailerUrls: string[] | null;
    userRating: number;
    views: number;
    workflowName: string;
    workflowStatus: string;
    workflowTrigger: string;
    writers: string[];
  }
  